// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es/el-aside')['default']
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElContainer: typeof import('element-plus/es/el-container')['default']
    ElFooter: typeof import('element-plus/es/el-footer')['default']
    ElHeader: typeof import('element-plus/es/el-header')['default']
    ElMain: typeof import('element-plus/es/el-main')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/layout/SideBar.vue')['default']
  }
}

export {}
